
services:
  vue-app:
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: task_manager_client
    environment:
      - HOST=0.0.0.0
